on:
  push:
  workflow_dispatch:
jobs:
  version_python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.version }}
      - run: python --version